name: test basics

on: 
  workflow_dispatch:

jobs:
  test-job1:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout-code
        uses: actions/checkout@v6

      - name: list repo files
        run: ls -lah

      - name: print
        run: echo "finished!"
  
