name: test-template

on: 
  workflow_dispatch:
env:
  GLOBAL_ENV: This is the global scope

jobs:
  job-1-test:
    runs-on: ubuntu-22.04
    env:
      JOB_ENV_SCOPE: This is the job-1-test scope
    steps:
      - name: first job
        env:
          STEP_ENV_SCOPE: This is job-1 step scope
        run: |
          echo "Scope test global: $GLOBAL_ENV"
          echo "Job test scope: $JOB_ENV_SCOPE"
          echo "Step test scope: $STEP_SCOPE"

  job-2-test:
    runs-on: ubuntu-22.04
    steps:
      - name: second job
        run: |
          echo "Scope test global: $GLOBAL_ENV"
          echo "Job test scope: $JOB_ENV_SCOPE"
          echo "Step test scope: $STEP_SCOPE"
